import type { FmpPlanValidationSnapshots } from "./fmp-plan-validation"

export const FMP_PLAN_VALIDATION_SNAPSHOTS: FmpPlanValidationSnapshots = {
  STARTER: {
    accessibleProbes: [
      "analyst-estimates",
      "commodity-intraday-5m",
      "commodity-quote",
      "crypto-intraday-5m",
      "crypto-quote",
      "dcf",
      "earnings-calendar",
      "economic-calendar",
      "employee-history",
      "financial-scores",
      "forex-intraday-5m",
      "forex-quote",
      "general-news",
      "grades-consensus",
      "insider-latest",
      "intraday-15min",
      "intraday-1hour",
      "intraday-30min",
      "intraday-4hour",
      "intraday-5min",
      "key-executives",
      "market-hours",
      "price-target-consensus",
      "product-segmentation",
      "quote",
      "risk-premium",
      "sec-filings",
      "sector-pe",
      "shares-float",
      "technical-rsi",
    ],
    capabilities: {
      realtimeQuotes: true,
      intradayCharts: true,
      technicalIndicators: true,
      batchQuotes: false,
      batchIndexQuotes: false,
      analystInsights: true,
      insiderTrades: false,
      latestInsiderFeed: true,
      ownership: false,
      etfAssetExposure: false,
      secFilings: true,
      economics: true,
      esgRatings: false,
      dcf: true,
      earningsTranscripts: false,
      pressReleases: false,
      companyExecutives: true,
      shareFloatLiquidity: true,
      cryptoMarkets: true,
      forexMarkets: true,
      commodityMarkets: true,
    },
    coverageScope: "us",
    intradayIntervals: [
      "5min",
      "15min",
      "30min",
      "1hour",
      "4hour",
    ],
    restrictedProbes: [
      "batch-index-quotes",
      "batch-quote",
      "earnings-transcripts",
      "esg-ratings",
      "etf-exposure",
      "insider-trading-symbol",
      "institutional-ownership",
      "intraday-1min",
      "press-releases",
    ],
    source: "pnpm markets:capabilities:write",
    validatedAt: "2026-03-29T22:48:45.892Z",
  },
}
