import type { FmpPlanValidationSnapshots } from "./fmp-plan-validation.ts"

export const FMP_PLAN_VALIDATION_SNAPSHOTS: FmpPlanValidationSnapshots = {
  STARTER: {
    accessibleDatasets: [
      "actively-trading-list",
      "aftermarket-quote",
      "aftermarket-trade",
      "all-exchange-market-hours",
      "analyst-estimates",
      "available-countries",
      "available-exchanges",
      "available-industries",
      "available-sectors",
      "balance-sheet-statement",
      "biggest-gainers",
      "biggest-losers",
      "cash-flow-statement",
      "commodity-historical-chart-5min",
      "commodity-quote",
      "company-screener",
      "crypto-historical-chart-5min",
      "crypto-quote",
      "dividends",
      "dividends-calendar",
      "earnings",
      "earnings-calendar",
      "economic-calendar",
      "economic-indicators",
      "employee-count",
      "enterprise-values",
      "etf-list",
      "exchange-market-hours",
      "financial-scores",
      "fmp-articles",
      "forex-historical-chart-5min",
      "forex-quote",
      "grades",
      "grades-consensus",
      "historical-chart-15min",
      "historical-chart-1hour",
      "historical-chart-30min",
      "historical-chart-4hour",
      "historical-chart-5min",
      "historical-employee-count",
      "historical-market-capitalization",
      "historical-price-eod-light",
      "historical-sector-performance",
      "holidays-by-exchange",
      "income-statement",
      "income-statement-growth",
      "insider-trading-latest",
      "ipos-calendar",
      "key-executives",
      "key-metrics-ttm",
      "levered-discounted-cash-flow",
      "market-risk-premium",
      "most-actives",
      "news-general-latest",
      "news-stock",
      "news-stock-latest",
      "owner-earnings",
      "price-target-consensus",
      "profile",
      "quote",
      "quote-short",
      "ratings-historical",
      "ratings-snapshot",
      "ratios-ttm",
      "revenue-geographic-segmentation",
      "revenue-product-segmentation",
      "search-name",
      "search-symbol",
      "sec-filings-search-symbol",
      "sec-profile",
      "sector-pe-snapshot",
      "sector-performance-snapshot",
      "shares-float",
      "splits",
      "splits-calendar",
      "stock-peers",
      "stock-price-change",
      "technical-indicators-rsi",
      "treasury-rates",
    ],
    accessibleProbes: [
      "actively-trading-list",
      "aftermarket-quote",
      "aftermarket-trade",
      "all-exchange-market-hours",
      "analyst-estimates",
      "available-countries",
      "available-exchanges",
      "available-industries",
      "available-sectors",
      "balance-sheet-statement",
      "biggest-gainers",
      "biggest-losers",
      "cash-flow-statement",
      "commodity-historical-chart-5min",
      "commodity-quote",
      "company-screener",
      "crypto-historical-chart-5min",
      "crypto-quote",
      "dividends",
      "dividends-calendar",
      "earnings",
      "earnings-calendar",
      "economic-calendar",
      "economic-indicators",
      "employee-count",
      "enterprise-values",
      "etf-list",
      "exchange-market-hours",
      "financial-scores",
      "fmp-articles",
      "forex-historical-chart-5min",
      "forex-quote",
      "grades",
      "grades-consensus",
      "historical-chart-15min",
      "historical-chart-1hour",
      "historical-chart-30min",
      "historical-chart-4hour",
      "historical-chart-5min",
      "historical-employee-count",
      "historical-market-capitalization",
      "historical-price-eod-light",
      "historical-sector-performance",
      "holidays-by-exchange",
      "income-statement",
      "income-statement-growth",
      "insider-trading-latest",
      "ipos-calendar",
      "key-executives",
      "key-metrics-ttm",
      "levered-discounted-cash-flow",
      "market-risk-premium",
      "most-actives",
      "news-general-latest",
      "news-stock",
      "news-stock-latest",
      "owner-earnings",
      "price-target-consensus",
      "profile",
      "quote",
      "quote-short",
      "ratings-historical",
      "ratings-snapshot",
      "ratios-ttm",
      "revenue-geographic-segmentation",
      "revenue-product-segmentation",
      "search-name",
      "search-symbol",
      "sec-filings-search-symbol",
      "sec-profile",
      "sector-pe-snapshot",
      "sector-performance-snapshot",
      "shares-float",
      "splits",
      "splits-calendar",
      "stock-peers",
      "stock-price-change",
      "technical-indicators-rsi",
      "treasury-rates",
    ],
    capabilities: {
      realtimeQuotes: true,
      intradayCharts: true,
      technicalIndicators: true,
      batchQuotes: false,
      batchIndexQuotes: false,
      analystInsights: true,
      insiderTrades: false,
      latestInsiderFeed: true,
      ownership: false,
      etfAssetExposure: false,
      secFilings: true,
      economics: true,
      esgRatings: false,
      dcf: true,
      earningsTranscripts: false,
      pressReleases: false,
      companyExecutives: true,
      shareFloatLiquidity: true,
      cryptoMarkets: true,
      forexMarkets: true,
      commodityMarkets: true,
      globalCoverage: false,
    },
    coverageScope: "us",
    intradayIntervals: [
      "5min",
      "15min",
      "30min",
      "1hour",
      "4hour",
    ],
    restrictedDatasets: [
      "batch-index-quotes",
      "batch-quote",
      "earning-call-transcript",
      "esg-ratings",
      "etf-asset-exposure",
      "historical-chart-1min",
      "insider-trading",
      "institutional-ownership",
      "news-press-releases",
    ],
    restrictedProbes: [
      "batch-index-quotes",
      "batch-quote",
      "earning-call-transcript",
      "esg-ratings",
      "etf-asset-exposure",
      "historical-chart-1min",
      "insider-trading",
      "institutional-ownership",
      "news-press-releases",
    ],
    source: "pnpm markets:capabilities:write",
    validatedAt: "2026-04-02T00:19:15.271Z",
  },
}
